#! /bin/bash
### BEGIN INIT INFO
# Provides:     lean-image
# Required-Start:   $syslog
# Required-Stop:    $syslog
# Should-Start:     $local_fs
# Should-Stop:      $local_fs
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    lean-image - image crop service
# Description:      lean-image - RESTful web service for image crop
### END INIT INFO


PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/opt/local/bin:$PATH
AS_USER="deploy"
APP_NAME="lean-image"
APP_HOME="/var/backends/lean-image/scripts"
PID_DIR="/var/run/${APP_NAME}"
LOG_DIR="/var/logs/${APP_NAME}"

if grep -i ubuntu /etc/issue > /dev/null; then
    AS_USER="ubuntu"
    APP_HOME="/mnt/leancloud/lean-image/scripts"
    PID_DIR="/var/run/${APP_NAME}"
    LOG_DIR="/mnt/leancloud/logs/${APP_NAME}"
fi

daemon_args="--name $APP_NAME --user $AS_USER --pidfile $PID_DIR/pid --stdout=$LOG_DIR/output.log --stderr=$LOG_DIR/error.log --chdir $APP_HOME"

function running() {
    #ps aux | grep imageService | grep -qv grep
    daemon $daemon_args --running
}

case "$1" in
     start)
        mkdir -p $PID_DIR
        mkdir -p $LOG_DIR
        chown -R $AS_USER $PID_DIR
        chown -R $AS_USER $LOG_DIR

        if running; then
            echo "$APP_NAME is already running."
            exit 0
        fi
        echo "Start $APP_NAME"
        echo "daemon $daemon_args -- $APP_HOME/start_service.sh"
        #$APP_HOME/start_service.sh&
        daemon $daemon_args -- $APP_HOME/start_service.sh
        if [ $? -eq 0 ] ; then
            echo "Starting $APP_NAME"
        else
            echo "failed to starting $APP_NAME"
        fi
        exit 0
        ;;
     stop)
        if ! running; then
            echo "$APP_NAME is not running."
            exit 0
        fi
        echo "Stop $APP_NAME"
        count=1
        while [ $count -le 5 ] && running;
        do
            echo "Stopping $APP_NAME $count times"
            daemon $daemon_args --stop
            (( count++ ))
            sleep 2;
        done
        if running; then
            echo "Tired, kill -9 $APP_NAME daemon `cat $PID_DIR/pid`"
            kill -9 `cat $PID_DIR/pid`
        fi
        $APP_HOME/stop_service.sh
        exit 0
        ;;
     restart)
        echo "Restart $APP_NAME"
        if running; then
            $0 stop
            sleep 1;
        fi
        if ! running; then
            $0 start
        fi
        exit 0
        ;;
     status)
        if ! running; then
            echo "$APP_NAME is not running"
        else
            echo "$APP_NAME is running"
        fi
        ;;
     *)
        echo "Usage: /etc/init.d/$APP_NAME {start|status|stop}" >&2
        exit 1
        ;;
esac

exit 0



