#ifndef AVOS_BACKEND_IMAGE_SERVICE_ERROR_CODE_INCLUDE_H_
#define AVOS_BACKEND_IMAGE_SERVICE_ERROR_CODE_INCLUDE_H_

typedef enum {
    EC_BAD_SIZE = -3,
    EC_CONVERT_FAILED = -2,
    EC_BUFFER_NOT_ENOUGH = -1,
    EC_OK = 0,
} ErrorCode;

#endif //end of AVOS_BACKEND_IMAGE_SERVICE_ERROR_CODE_INCLUDE_H_
